global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'supply-chain-monitor'

rule_files: []

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'api-gateway'

  - job_name: 'supplier-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['supplier-service:8081']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'supplier-service'

  - job_name: 'inventory-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['inventory-service:8082']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'inventory-service'

  - job_name: 'blockchain-ledger-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['blockchain-ledger-service:8083']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'blockchain-ledger-service'
